### ISSUE TITLE
Fullname.c

### ISSUE THREAD

**Issue by tonyiovino** [tonyiovino/helloworld_c#1]
Al momento di "git push origin master", mi esce codesta scrtitta:
Username for 'https://github.com': tonyiovino
Password for 'https://tonyiovino@github.com': 
To https://github.com/tonyiovino/helloworld_c.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://github.com/tonyiovino/helloworld_c.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

**Comment by FabioZTessitore** [comment]
certo. Perché hai fatto delle modifiche sul sito (che già ti avevo detto di non fare).
Cmq si risolve facile. Rifai il clone e continua

**Comment by tonyiovino** [comment]
Okay!

Il giorno Mer 8 Mag 2019 18:05 Fabio Z Tessitore <notifications@github.com>
ha scritto:

**Comment by tonyiovino** [comment]
Eccovi il mio primo programmino in codice C.
