### ISSUE TITLE
Figure.c

### ISSUE THREAD

**Issue by tonyiovino** [tonyiovino/helloworld_c#2]
Vedete la repository, che ho finito anche "figure.c"

**Comment by FabioZTessitore** [comment]
devi aggiungermi come collaboratore

**Comment by tonyiovino** [comment]
Ehm... si.
Prof. ho l'ora disponibile, il professore mi ha dato il permesso, visto che
è sostitolone. Posso venire da voi, o siete occupati?


Il giorno Sab 11 Mag 2019 09:32 Fabio Z Tessitore <notifications@github.com>
ha scritto:

**Comment by FabioZTessitore** [comment]
Per fare?

Il sab 11 mag 2019, 10:07 tonyiovino <notifications@github.com> ha scritto:

**Comment by tonyiovino** [comment]
Le variabili in codice C

Il giorno Sab 11 Mag 2019 10:10 Fabio Z Tessitore <notifications@github.com>
ha scritto:

**Comment by tonyiovino** [comment]
Spero solo di non infastidirvi

Il giorno Sab 11 Mag 2019 10:13 Tjony Official <
antonioiovino2004tony@gmail.com> ha scritto:
