### ISSUE TITLE
operazioni

### ISSUE THREAD

**Issue by FabioZTessitore** [tonyiovino/helloworld_c#3]
quante sono le operazioni elementari?

**Comment by tonyiovino** [comment]
Ehm... Quattro?

**Comment by FabioZTessitore** [comment]
Ehm no

Il lun 13 mag 2019, 17:52 tonyiovino <notifications@github.com> ha scritto:

**Comment by tonyiovino** [comment]
E quante ne sono?

**Comment by tonyiovino** [comment]
http://staff.matapp.unimib.it/~paoletti/alg-geom/operazioni-elementari.pdf
Ho visto su google, ma non capisco...

**Comment by tonyiovino** [comment]
Forse il resto?

**Comment by FabioZTessitore** [comment]
In python quante ne hai viste?

Il lun 13 mag 2019, 17:55 tonyiovino <notifications@github.com> ha scritto:

**Comment by FabioZTessitore** [comment]
Il resto è la quinta

Il lun 13 mag 2019, 18:00 Fabio Z Tessitore <fabioztessitore@gmail.com> ha
scritto:

**Comment by tonyiovino** [comment]
In python ne ho visto 6:
Somma
Differenza
Prodotto
Quoto o quoziente
Radice quadrata

**Comment by FabioZTessitore** [comment]
La radice quadrata l'hai fatta mediante una funzione, non è considerata
operazione elementare

Il lun 13 mag 2019, 18:04 tonyiovino <notifications@github.com> ha scritto:

**Comment by tonyiovino** [comment]
E anche il resto*

**Comment by tonyiovino** [comment]
Ah, allora ne sono 5: +, -, *, /, &.

**Comment by tonyiovino** [comment]
Perchè quando lo eseguo, non mi da' il resto?

**Comment by FabioZTessitore** [comment]
```c
printf("%d % %d = %d\n", numero1, numero2, resto);
```

Il problema è qui. Il carattere `%` serve ad indicare le specifiche di stampa. Se vuoi stamparlo devi scrivere `%%`

**Comment by tonyiovino** [comment]
Aah. Ho capito. Il tempo che accendo il computer.

Il giorno Lun 13 Mag 2019 21:44 Fabio Z Tessitore <notifications@github.com>
ha scritto:

**Comment by tonyiovino** [comment]
Ecco fatto!
