### ISSUE TITLE
cerchio.c

### ISSUE THREAD

**Issue by tonyiovino** [tonyiovino/helloworld_c#4]

**Comment by tonyiovino** [comment]
Vorrei sapere come calcolare la circonferenza avendo il raggio.

**Comment by FabioZTessitore** [comment]
Facciamo una ricerca su, è cosa di scuola media

Il mer 15 mag 2019, 19:02 tonyiovino <notifications@github.com> ha scritto:

**Comment by tonyiovino** [comment]
Vabene!

**Comment by tonyiovino** [comment]
2 * pigreco * r

**Comment by FabioZTessitore** [comment]
Ok

Il mer 15 mag 2019, 19:16 tonyiovino <notifications@github.com> ha scritto:

**Comment by tonyiovino** [comment]
Ecco.
