### ISSUE TITLE
maggiore2

### ISSUE THREAD

**Issue by FabioZTessitore** [tonyiovino/helloworld_c#5]
bisogna eliminare l'else come già sai. Spremiamo il cervello

**Comment by tonyiovino** [comment]
Mh...

**Comment by tonyiovino** [comment]
Non riesco, mi viene sempre da usare else... :(

**Comment by FabioZTessitore** [comment]
spremi spremi

**Comment by tonyiovino** [comment]
C'è un comando che calcola già il numero più grande?

Il Lun 20 Mag 2019 10:02 Fabio Z Tessitore <notifications@github.com> ha
scritto:

**Comment by FabioZTessitore** [comment]
No

Il lun 20 mag 2019, 10:18 tonyiovino <notifications@github.com> ha scritto:

**Comment by tonyiovino** [comment]
Ci vogliono gli operatori logici?

Il Lun 20 Mag 2019 10:24 Fabio Z Tessitore <notifications@github.com> ha
scritto:

**Comment by FabioZTessitore** [comment]
No. Solo un if semplice semplice

Il lun 20 mag 2019, 10:30 tonyiovino <notifications@github.com> ha scritto:

**Comment by tonyiovino** [comment]
Gli "int" sono solo numero1 e numero2?

Il Lun 20 Mag 2019 10:31 Fabio Z Tessitore <notifications@github.com> ha
scritto:

**Comment by FabioZTessitore** [comment]
num1 e num2 sono i dati. Se hai bisogno di altre variabili puoi usarle

Il lun 20 mag 2019, 10:33 tonyiovino <notifications@github.com> ha scritto:

**Comment by tonyiovino** [comment]
include <stdio.h>

int main ()

    int numero+, numero-;

{
    printf("Inserisca il numero più grande");
    scanf("%d", numero+);
    printf("Inserisca il numero più piccolo del numero precedente");
    scanf("%d", numero-);

    if (numero+ > numero-)
{
    printf("il numero %d è più grande del numero %d", numero+, numero-\n);
}
    return 0;
}

Il Lun 20 Mag 2019 10:40 Fabio Z Tessitore <notifications@github.com> ha
scritto:

**Comment by tonyiovino** [comment]
Va bene così?  😂😂😂

Il Lun 20 Mag 2019 10:56 Tjony Official <antonioiovino2004tony@gmail.com>
ha scritto:

**Comment by FabioZTessitore** [comment]
Questo è un imbroglio

Il lun 20 mag 2019, 10:57 tonyiovino <notifications@github.com> ha scritto:

**Comment by tonyiovino** [comment]
Hahahaha, si, mi sto cervellando ma non riesco 😥

Il Lun 20 Mag 2019 11:05 Fabio Z Tessitore <notifications@github.com> ha
scritto:

**Comment by tonyiovino** [comment]
Idea!

**Comment by tonyiovino** [comment]
Oggi, visto che non avevo il mio computer, ho provato a farla alla lavagna
insieme al prof.

Il Lun 20 Mag 2019 11:07 Tjony Official <antonioiovino2004tony@gmail.com>
ha scritto:

**Comment by FabioZTessitore** [comment]
l'esercizio va bene ma hai aggiunto un paio di parentesi che non hanno alcun senso se non confondere chi legge. Toglile e allinea la printf al resto del codice

**Comment by tonyiovino** [comment]
Ora?
Le avevo messe perché dove ho studiato le "if, else, else if" le parentesi sono messe come le ho messe io.

**Comment by FabioZTessitore** [comment]
Vorrei che fosse chiaro che hai usato l'if senza parentesi graffe perché al suo interno c'è un'unica istruzione. La printf viene eseguita in ogni caso, quindi non ha senso che stia spostata a destra.
Se questa cosa non ti è chiara parliamone

**Comment by tonyiovino** [comment]
Quindi se all'interno dell'if ci fossero state più istruzioni, in quel caso sarebbe stato giusto mettere le parentesi graffe?

**Comment by FabioZTessitore** [comment]
Le parentesi graffe servono a creare blocchi di codice. Un blocco di codice si può usare laddove si può usare un'istruzione.
Una if vuole un'istruzione a seguire. Quindi per far eseguire più istruzioni possiamo usare un blocco.

```c
if (condizione) {
    blocco di istruzioni
}
```

Se hai veramente una sola istruzione conviene mettere comunque le graffe. In questo modo se decidi di aggiungere altre istruzioni non fai errori. Inoltre in un caso come il tuo non ci sarebbero ambiguità:

```c
if (b > a) max = b;
    printf("ciao");    /* e' spostata a destra, ma non e' in parentesi.
                                cosa voleva fare il programmatore? fa parte dell'if? */
```

E' ammesso omettere le parentesi graffe se hai una sola istruzione e la metti sullo stesso rigo dell'if, ma devi scrivere correttamente ciò che segue.

```c
if (b > a) max = b;

printf("ciao");    /* NON e' spostata a destra, c'e' anche un a capo */
```

**Comment by tonyiovino** [comment]
Ora mi è chiaro, grazie!
