### ISSUE TITLE
somma cifre

### ISSUE THREAD

**Issue by FabioZTessitore** [tonyiovino/helloworld_c#7]
gitignore

il numero deve essere inserito come int, un solo int e devi controllare se ha più di tre cifre o no

**Comment by tonyiovino** [comment]
Wow, non potete crederci, ma ho appena abbassato la finestra delle
notifiche per cercare la vostra mail, e all'improvviso mi spunta
"FabioZTessitore" 😂

Il Gio 23 Mag 2019 19:29 Fabio Z Tessitore <notifications@github.com> ha
scritto:

**Comment by tonyiovino** [comment]
Come faccio a ottenere le cifre senza neanche dichiararle come variabili?

**Comment by FabioZTessitore** [comment]
Questo è il problema. Hai ad esempio il numero 123. Come facciamo ad
ottenere 1 2 e 3?
Suggerimento: inizia da destra. Cerca un modo per ottenere il 3

Il gio 23 mag 2019, 20:31 tonyiovino <notifications@github.com> ha scritto:

**Comment by tonyiovino** [comment]
Dividendo per 10 e con un comando magico che prende il numero decimale?

Il Gio 23 Mag 2019 20:45 Fabio Z Tessitore <notifications@github.com> ha
scritto:

**Comment by FabioZTessitore** [comment]
Fuochino

Il gio 23 mag 2019, 21:15 tonyiovino <notifications@github.com> ha scritto:

**Comment by tonyiovino** [comment]
Ehm...
Un codice magico che serve a un codice magico!
Seriamente... A che fare con il resto?

Il Gio 23 Mag 2019 21:37 Fabio Z Tessitore <notifications@github.com> ha
scritto:

**Comment by FabioZTessitore** [comment]
Si

Il gio 23 mag 2019, 21:40 tonyiovino <notifications@github.com> ha scritto:

**Comment by tonyiovino** [comment]
Okay...
Il numero devo dividerlo?

**Comment by FabioZTessitore** [comment]
devi riuscire a trovare a1, a2 e a3 in qualche modo. Hai scoperto che il resto della divisione ti può aiutare. Ora continua su questa strada

**Comment by tonyiovino** [comment]
Usare queste due operazioni per ottenere a1, a2, a3?

Il Ven 24 Mag 2019 13:48 Fabio Z Tessitore <notifications@github.com> ha
scritto:

**Comment by FabioZTessitore** [comment]
Si

Il ven 24 mag 2019, 14:46 tonyiovino <notifications@github.com> ha scritto:

**Comment by tonyiovino** [comment]
Quale per prima? 😅

Il Ven 24 Mag 2019 14:55 Fabio Z Tessitore <notifications@github.com> ha
scritto:

**Comment by tonyiovino** [comment]
Ma poi... a = a1 % ... ? 100?

Il Ven 24 Mag 2019 14:56 Tjony Official <antonioiovino2004tony@gmail.com>
ha scritto:

**Comment by FabioZTessitore** [comment]
tony devi ragionare sennò non serve a niente.
Hai `a` che vale 123 ad esempio.
Se fai `a%10` puoi ottenere il 3 e decidi in che variabile metterlo.
A questo punto devi trovare un modo per riuscire ad ottenere il 2 e poi l'1. Li metti nelle altre variabili e sommi

**Comment by tonyiovino** [comment]
Ho preso carta, penna e ci sono riuscito.   :-)
